spring:
  redis:
    host: 101.200.229.194
    port: 6379
    password: slayerd
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1000
        min-idle: 0
server:
  port: 8001